name: Update plugins database

on:
  schedule:
    - cron: '0 0/4 * * *'
  workflow_dispatch:

jobs:
  regenerate-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: plugman
        
      - name: Install dependencies
        run: |
          sudo apt update -q
          sudo apt install -y -q python3 python3-pip
          sudo pip3 install requests

      - name: Regenerate database
        run: |
          cd ./plugman
          CLIENT_ID=${{ secrets.CLIENT_ID }} CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} python3 generate_database.py

      - name: Commit database changes
        run: |
          cd ./plugman
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ ! -z $(git status -s) ]]; then
            git add database.json
            git commit -m "chore: update plugins database"
          fi
      - name: Push regenerated database
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: ./plugman
